# Generated by Django 4.2.16 on 2024-11-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="titile",
            new_name="title",
        ),
    ]
